site_name: Ansible Automation Platform Workshop Guide

theme:
  name: material
  logo: images/logo.png                    # Path to your logo (see below)
  favicon: images/RH_AAP_Logo.png 
  home_url: /              # Optional: browser tab icon
  palette:
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default                      # Light mode option
      primary: white
      text_color: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - content.code.copy                    # Copy button on code blocks
    - content.code.select                  # Select all code in block

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true                       # Show line numbers
  - pymdownx.superfences                   # Better code fence handling
  - pymdownx.inlinehilite                  # Inline code highlighting
  - admonition          # <-- ADD THIS
  - pymdownx.details    # <-- ADD THIS (for collapsible)
nav:
  # - Ansible Automation Platform Workshop Guide: index.md
  - Lab Guide Home: index.md
  - Understanding the lab setup: 1-setup/index.md
  - Ansible Basics: 2-thebasics/index.md
  - Exercise 1 - First playbook: 3-playbook/index.md
  - Exercise 2 - First Automation Job: 4-projects/index.md
  - Exercise 3 - User Inputs: 5-surveys/index.md
  - Bonus Exercise 4 - Workflows: 6-bonus-workflows/index.md

extra_css:
  - stylesheets/extra.css